service: TDevPoller
provider:
  name: aws
  runtime: python2.7
  region: ap-southeast-2
  environment:
    DATA_BUCKET: s3-data-bucket-name
  iamRoleStatements:
    - Effect: "Allow" 
      Action: "logs:*"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: "Allow" 
      Action: "ssm:*"
      Resource: "*"
    - Effect: "Allow" 
      Action: "s3:*"
      Resource: "*"

functions:
  poll_devices:
    handler: poll_devices.handler
    timeout: 60
    events:
      - schedule: rate(5 minutes)

custom:
  pythonRequirements:
    dockerizePip: false

plugins:
  - serverless-python-requirements
